-- 버스 정보를 가지는 테이블
DROP TABLE bus;

CREATE TABLE bus(
	routId			NUMBER			CONSTRAINT BUS_RTID_PK PRIMARY KEY,
	routName		VARCHAR2(30)	CONSTRAINT BUS_RTNAME_UNI UNIQUE,
	routType		VARCHAR2(10),
	stnFirst		VARCHAR2(100),
	stnLast			VARCHAR2(100),
	busIntervals	CHAR(4),
	timeFirst		CHAR(4),
	timeLast		CHAR(4),
	satTimeFirst	CHAR(4),
	satTimeLast		CHAR(4),
	holTimeFirst	CHAR(4),
	holTimeLast		CHAR(4),
	norTerms		VARCHAR2(20),
	satTerms		VARCHAR2(20),
	holTerms		VARCHAR2(20),
	companyNm		VARCHAR2(30),
	telNo			VARCHAR2(30),
	faxNo			VARCHAR2(30),
	email			VARCHAR2(100)
);

insert /*+ IGNORE_ROW_ON_DUPKEY_INDEX (bus(routId)) */ into bus values (
	SELECT routId
	FROM bus
);

CREATE TABLE bus(
	routId			NUMBER			CONSTRAINT BUS_RTID_PK PRIMARY KEY,
	routName		VARCHAR2(30)	CONSTRAINT BUS_RTNAME_UNI UNIQUE,
	routType		VARCHAR2(10)	CONSTRAINT BUS_RTTYPE_NN NOT NULL,
	stnFirst		VARCHAR2(100)	CONSTRAINT BUS_STNFIRST_NN NOT NULL,
	stnLast			VARCHAR2(100)	CONSTRAINT BUS_STNLAST_NN NOT NULL,
	busIntervals	CHAR(4)			CONSTRAINT BUS_INTERVAL_NN NOT NULL,
	timeFirst		CHAR(4)			CONSTRAINT BUS_TIMEFIRST_NN NOT NULL,
	timeLast		CHAR(4)			CONSTRAINT BUS_TIMELAST_NN NOT NULL,
	satTimeFirst	CHAR(4)			CONSTRAINT BUS_SATTIMEFIRST_NN NOT NULL,
	satTimeLast		CHAR(4)			CONSTRAINT BUS_SATTIMELAST_NN NOT NULL,
	holTimeFirst	CHAR(4)			CONSTRAINT BUS_HOLTIMEFIRST_NN NOT NULL,
	holTimeLast		CHAR(4)			CONSTRAINT BUS_HOLTIMELAST_NN NOT NULL,
	norTerms		VARCHAR2(20)	CONSTRAINT BUS_NORTERMS_NN NOT NULL,
	satTerms		VARCHAR2(20)	CONSTRAINT BUS_SATTERMS_NN NOT NULL,
	holTerms		VARCHAR2(20)	CONSTRAINT BUS_HOLTERMS_NN NOT NULL,
	companyNm		VARCHAR2(30)	CONSTRAINT BUS_COMNAME_NN NOT NULL,
	telNo			VARCHAR2(30),
	faxNo			VARCHAR2(30),
	email			VARCHAR2(100)
);

-- 정류장 정보를 가지는 테이블

-- 즐겨찾기 정보를 가지는 테이블

-- 최근 검색 기록을 가지는 테이블